VibbraPlaces.Web/Controllers/EvaluationController.cs
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;
using VibbraPlaces.Web.Data.Context;
using VibbraPlaces.Web.Models.Evaluation;

namespace VibbraPlaces.Web.Controllers
{
    public class EvaluationController : Controller
    {
        private ApplicationDbContext dbContext = new ApplicationDbContext();

        public ActionResult Index()
        {
            var dbContext = new ApplicationDbContext();

            var placeTypes = dbContext.PlaceTypes.OrderBy(p => p.Name).ToList();
            placeTypes.Insert(0, new Data.Model.PlaceType() { Id = 0, Name = "Todos" });

            var priceRating = new[]
            {
                new SelectListItem { Value = "0", Text = "Todos" },
                new SelectListItem { Value = "1", Text = "$" },
                new SelectListItem { Value = "2", Text = "$$" },
                new SelectListItem { Value = "3", Text = "$$$" },
                new SelectListItem { Value = "4", Text = "$$$$" },
                new SelectListItem { Value = "5", Text = "$$$$$" },

            };

            ViewBag.PlaceTypes = placeTypes;
            ViewBag.PriceRating = priceRating;

            var evaluations = dbContext.PlaceEvaluations.ToList();

            var findVM = new FindEvaluationVM();
            foreach (var evaluation in evaluations)
            {
                findVM.Evaluations.Add(new EvaluationVM()
                {
                    Id = evaluation.Id,
                    PlaceId = evaluation.PlaceId,
                    Name = evaluation.Place.Name,
                    Type = evaluation.Place.PlaceType.Name,
                    City = evaluation.Place.City,
                    State = evaluation.Place.State,
                    PriceRating = evaluation.PriceRating,
                    GeneralRating = evaluation.GeneralEvaluationRating,
                    HasInternet = evaluation.HasInternet
                });
            }

            return View(findVM);
        }

        [HttpPost]
        public ActionResult Index(FindEvaluationVM model)
        {
            var dbContext = new ApplicationDbContext();

            var placeTypes = dbContext.PlaceTypes.OrderBy(p => p.Name).ToList();
            placeTypes.Insert(0, new Data.Model.PlaceType() { Id = 0, Name = "Todos" });

            var priceRating = new[]
            {
                new SelectListItem { Value = "0", Text = "Todos" },
                new SelectListItem { Value = "1", Text = "$" },
                new SelectListItem { Value = "2", Text = "$$" },
                new SelectListItem { Value = "3", Text = "$$$" },
                new SelectListItem { Value = "4", Text = "$$$$" },
                new SelectListItem { Value = "5", Text = "$$$$$" },

            };

            ViewBag.PlaceTypes = placeTypes;
            ViewBag.PriceRating = priceRating;

            if (model.Term == null)
                model.Term = string.Empty;

            var evaluations = dbContext.PlaceEvaluations
                .Where(p => (
                p.Place.Name.Contains(model.Term) ||
                p.Place.City.Contains(model.Term))
                && (model.PlaceType == 0 || p.Place.PlaceTypeId == model.PlaceType)
                && (model.Price == 0 || p.PriceRating == model.Price)
                )
                .ToList();

            foreach (var evaluation in evaluations)
            {
                model.Evaluations.Add(new EvaluationVM()
                {
                    Id = evaluation.Id,
                    PlaceId = evaluation.PlaceId,
                    Name = evaluation.Place.Name,
                    Type = evaluation.Place.PlaceType.Name,
                    City = evaluation.Place.City,
                    State = evaluation.Place.State,
                    PriceRating = evaluation.PriceRating,
                    GeneralRating = evaluation.GeneralEvaluationRating,
                    HasInternet = evaluation.HasInternet
                });
            }

            return View(model);
        }

        [Authorize]
        public ActionResult Mine()
        {
            var dbContext = new ApplicationDbContext();

            var userId = User.Identity.GetUserId<long>();
            var evaluations = dbContext.PlaceEvaluations.Where(e => e.ApplicationUserId == userId).ToList();

            var findVM = new FindEvaluationVM();
            foreach (var evaluation in evaluations)
            {
                findVM.Evaluations.Add(new EvaluationVM()
                {
                    Id = evaluation.Id,
                    PlaceId = evaluation.PlaceId,
                    Name = evaluation.Place.Name,
                    Type = evaluation.Place.PlaceType.Name,
                    City = evaluation.Place.City,
                    State = evaluation.Place.State,
                    PriceRating = evaluation.PriceRating,
                    GeneralRating = evaluation.GeneralEvaluationRating,
                    HasInternet = evaluation.HasInternet
                });
            }

            return View(findVM);
        }
    }
}

VibbraPlaces.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VibbraPlaces</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VibbraPlaces", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Busca", "Index", "Home")</li>
                        <li>@Html.ActionLink("Avaliações", "Index", "Evaluation")</li>
                        <li>@Html.ActionLink("Minhas Avaliações", "Mine", "Evaluation")</li>
                        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Busca", "Index", "Home")</li>
                        <li>@Html.ActionLink("Avaliações", "Index", "Evaluation")</li>
                        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VibbraPlaces</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VibbraPlaces.Web/Views/Shared/_Messages.cshtml
@if (TempData["SuccessMessage"] != null && TempData["SuccessMessage"] != "")
{
    <div role="alert" class="alert alert-success alert-dismissible fade in">
        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true">×</span>
        </button>
        &nbsp;
        <em id="info" class="fa fa-check"></em>
        &nbsp;
        @Html.Raw(@TempData["SuccessMessage"])
    </div>
}

@if (TempData["ErrorMessage"] != null && TempData["ErrorMessage"] != "")
{
    <div role="alert" class="alert alert-danger alert-dismissible fade in">
        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true">×</span>
        </button>
        &nbsp;
        <em id="info" class="fa fa-exclamation-triangle"></em>
        &nbsp;
        @Html.Raw(@TempData["ErrorMessage"])
    </div>
}

@if (TempData["InfoMessage"] != null && TempData["InfoMessage"] != "")
{
    <div role="alert" class="alert alert-info alert-dismissible fade in">
        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
            <span aria-hidden="true">×</span>
        </button>
        &nbsp;
        <em id="info" class="fa fa-info"></em>
        &nbsp;
        @Html.Raw(@TempData["InfoMessage"])
    </div>
}