VibbraPlaces.Web/Models/Home/FindVM.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VibbraPlaces.Web.Models.Home
{
    public class FindVM
    {
        public FindVM()
        {
            Places = new List<PlaceVM>();
        }

        [Display(Name = "Nome ou endereço")]
        public string Term { get; set; }

        [Display(Name = "Tipo de Local")]
        public int PlaceType { get; set; }

        [Display(Name = "Valor")]
        public int Price { get; set; }

        public List<PlaceVM> Places { get; set; }
    }

    public class PlaceVM
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int EvaluationQuantity { get; set; }
    }
}

VibbraPlaces.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VibbraPlaces.Web.Data.Context;
using VibbraPlaces.Web.Models.Home;

namespace VibbraPlaces.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var dbContext = new ApplicationDbContext();

            var placeTypes = dbContext.PlaceTypes.OrderBy(p => p.Name).ToList();
            placeTypes.Insert(0, new Data.Model.PlaceType() { Id = 0, Name = "Todos" });

            var priceRating = new[]
            {
                new SelectListItem { Value = "0", Text = "Todos" },
                new SelectListItem { Value = "1", Text = "$" },
                new SelectListItem { Value = "2", Text = "$$" },
                new SelectListItem { Value = "3", Text = "$$$" },
                new SelectListItem { Value = "4", Text = "$$$$" },
                new SelectListItem { Value = "5", Text = "$$$$$" },

            };

            ViewBag.PlaceTypes = placeTypes;
            ViewBag.PriceRating = priceRating;

            var places = dbContext.Places.ToList();

            var findVM = new FindVM();
            foreach (var place in places)
            {
                findVM.Places.Add(new PlaceVM()
                {
                    Id = place.Id,
                    Name = place.Name,
                    Type = place.PlaceType.Name,
                    City = place.City,
                    State = place.State,
                    EvaluationQuantity = place.PlaceEvaluations.Count()
                });
            }

            return View(findVM);
        }

        [HttpPost]
        public ActionResult Index(FindVM model)
        {
            var dbContext = new ApplicationDbContext();

            var placeTypes = dbContext.PlaceTypes.OrderBy(p => p.Name).ToList();
            placeTypes.Insert(0, new Data.Model.PlaceType() { Id = 0, Name = "Todos" });

            var priceRating = new[]
            {
                new SelectListItem { Value = "0", Text = "Todos" },
                new SelectListItem { Value = "1", Text = "$" },
                new SelectListItem { Value = "2", Text = "$$" },
                new SelectListItem { Value = "3", Text = "$$$" },
                new SelectListItem { Value = "4", Text = "$$$$" },
                new SelectListItem { Value = "5", Text = "$$$$$" },

            };

            ViewBag.PlaceTypes = placeTypes;
            ViewBag.PriceRating = priceRating;

            if (model.Term == null)
                model.Term = string.Empty;

            var places = dbContext.Places
                .Where(p => (
                p.Name.Contains(model.Term) ||
                p.City.Contains(model.Term))
                && (model.PlaceType == 0 || p.PlaceTypeId == model.PlaceType))
                .ToList();

            foreach (var place in places)
            {
                model.Places.Add(new PlaceVM()
                {
                    Id = place.Id,
                    Name = place.Name,
                    Type = place.PlaceType.Name,
                    City = place.City,
                    State = place.State,
                    EvaluationQuantity = place.PlaceEvaluations.Count()
                });
            }

            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VibbraPlaces.Web/Controllers/PlaceController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Web.Mvc;
using VibbraPlaces.Web.Data.Context;
using VibbraPlaces.Web.Data.Model;
using VibbraPlaces.Web.Models.Place;

namespace VibbraPlaces.Web.Controllers
{
    [Authorize]
    public class PlaceController : Controller
    {
        private ApplicationDbContext dbContext = new ApplicationDbContext();

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.placeTypes = dbContext.PlaceTypes.OrderBy(p => p.Name).ToList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePlaceVM model)
        {
            ViewBag.placeTypes = dbContext.PlaceTypes.OrderBy(p => p.Name).ToList();

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var place = new Place()
                {
                    Name = model.Name,
                    Address = model.Address,
                    City = model.City,
                    State = model.State,
                    Country = model.Country,
                    PlaceTypeId = model.PlaceTypeId,
                    InsertDate = DateTime.Now,
                    ApplicationUserId = User.Identity.GetUserId<long>()
                };

                dbContext.Places.Add(place);
                dbContext.SaveChanges();

                TempData["SuccessMessage"] = "Estabelecimento cadastrado com sucesso";
                return RedirectToAction("evaluate", "place", new { id = place.Id });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Evaluate(long id)
        {
            var userId = User.Identity.GetUserId<long>();
            var placeEvaluation = dbContext.PlaceEvaluations.Where(p => p.PlaceId == id && p.ApplicationUserId == userId).FirstOrDefault();

            if (placeEvaluation == null)
            {
                var place = dbContext.Places.Where(p => p.Id == id).FirstOrDefault();

                if (place == null)
                    return HttpNotFound();

                var evaluatePlaceVM = new EvaluatePlaceVM()
                {
                    PlaceId = place.Id,
                    Name = place.Name,
                    Address = place.Address,
                    City = place.City,
                    Country = place.Country,
                    State = place.State,
                    PlaceType = place.PlaceType.Name
                };

                return View(evaluatePlaceVM);
            }
            else
            {
                var evaluatePlaceVM = new EvaluatePlaceVM()
                {
                    PlaceId = placeEvaluation.Place.Id,
                    Name = placeEvaluation.Place.Name,
                    Address = placeEvaluation.Place.Address,
                    City = placeEvaluation.Place.City,
                    Country = placeEvaluation.Place.Country,
                    State = placeEvaluation.Place.State,
                    PlaceType = placeEvaluation.Place.PlaceType.Name,

                    EvaluateId = placeEvaluation.Id,
                    HasInternet = placeEvaluation.HasInternet,
                    InternetSpeed = placeEvaluation.InternetSpeed,
                    OpenInternet = placeEvaluation.OpenInternet,
                    InternetPassword = placeEvaluation.InternetPassword,
                    Food = placeEvaluation.Food,
                    Drink = placeEvaluation.Drink,
                    ServiceRating = placeEvaluation.ServiceRating,
                    PriceRating = placeEvaluation.PriceRating,
                    ComfortRating = placeEvaluation.ComfortRating,
                    NoiseRating = placeEvaluation.NoiseRating,
                    GeneralEvaluationRating = placeEvaluation.GeneralEvaluationRating
                };

                return View(evaluatePlaceVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Evaluate(EvaluatePlaceVM model)
        {
            var place = dbContext.Places.Where(p => p.Id == model.PlaceId).FirstOrDefault();
            model.Name = place.Name;
            model.Address = place.Address;
            model.City = place.City;
            model.Country = place.Country;
            model.State = place.State;
            model.PlaceType = place.PlaceType.Name;

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                if (model.EvaluateId.Equals(0))
                {
                    var placeEvaluation = new PlaceEvaluation()
                    {
                        PlaceId = model.PlaceId,
                        HasInternet = model.HasInternet,
                        InternetSpeed = model.InternetSpeed,
                        OpenInternet = model.OpenInternet,
                        InternetPassword = model.InternetPassword,
                        Food = model.Food,
                        Drink = model.Drink,
                        ServiceRating = model.ServiceRating,
                        PriceRating = model.PriceRating,
                        ComfortRating = model.ComfortRating,
                        NoiseRating = model.NoiseRating,
                        GeneralEvaluationRating = model.GeneralEvaluationRating,
                        InsertDate = DateTime.Now,
                        ApplicationUserId = User.Identity.GetUserId<long>()
                    };

                    dbContext.PlaceEvaluations.Add(placeEvaluation);
                    dbContext.SaveChanges();

                    TempData["SuccessMessage"] = "Avaliação cadastrada com sucesso";
                    return RedirectToAction("mine", "evaluation");
                }
                else
                {
                    var placeEvaluation = dbContext.PlaceEvaluations.Where(p => p.Id == model.EvaluateId).FirstOrDefault();

                    placeEvaluation.HasInternet = model.HasInternet;
                    placeEvaluation.InternetPassword = model.InternetSpeed;
                    placeEvaluation.OpenInternet = model.OpenInternet;
                    placeEvaluation.InternetPassword = model.InternetPassword;
                    placeEvaluation.Food = model.Food;
                    placeEvaluation.Drink = model.Drink;
                    placeEvaluation.ServiceRating = model.ServiceRating;
                    placeEvaluation.PriceRating = model.PriceRating;
                    placeEvaluation.ComfortRating = model.ComfortRating;
                    placeEvaluation.NoiseRating = model.NoiseRating;
                    placeEvaluation.GeneralEvaluationRating = model.GeneralEvaluationRating;
                    placeEvaluation.UpdateDate = DateTime.Now;

                    dbContext.SaveChanges();

                    TempData["SuccessMessage"] = "Avaliação atualizada com sucesso";
                    return RedirectToAction("mine", "evaluation");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }
                
        [HttpGet]
        [AllowAnonymous]
        public ActionResult View(long id)
        {
            var place = dbContext.Places.Where(p => p.Id == id).FirstOrDefault();

            if (place == null)
                return HttpNotFound();

            return View(place);
        }

        [HttpGet]
        [AllowAnonymous]
        [ActionName("view-evaluation")]
        public ActionResult ViewEvaluation(long id)
        {
            var evaluation = dbContext.PlaceEvaluations.Where(p => p.Id == id).FirstOrDefault();

            if (evaluation == null)
                return HttpNotFound();

            return View(evaluation);
        }
    }
}

VibbraPlaces.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>Vibbra Places</h2>
<p>
    Vibbra Places é uma plataforma para profissionais que precisam de um lugar
    apropriado para trabalhar, ou seja, pessoas
    que trabalham remotamente, que viajam,
    profissionais liberais, pessoas que gostam
    de variar o seu local de trabalho etc.
</p>

<p>Em caso de dúvidas entre em contato conosco pelo e-mail srvibbraneo@gmail.com.</p>

VibbraPlaces.Web/Views/Home/Index.cshtml
@model VibbraPlaces.Web.Models.Home.FindVM
@{
    ViewBag.Title = "Locais incríveis para trabalhar remoto";
}

@if (Request.HttpMethod == "GET")
{
    <div class="alert alert-info alert-dismissible" role="alert">
        <h2>Bem-vindo ao Vibbra Places!</h2>
        <p class="lead">Encontre lugares incríveis para trabalhar remoto. Veja a avaliação de outros profissionais e avalie seus locais de trabalho.</p>
    </div>
}
else
{
    <br />
}

@Html.Partial("_Messages")

<div class="alert alert-success" role="alert">
    <p><b>Buscar Estabelecimentos</b></p>
    <hr style="margin: 2px">

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Index", "Home", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="row">
                    <div class="col-md-8">
                        @Html.LabelFor(m => m.Term, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.Term, new { @class = "form-control", placeholder = "Nome do local ou endereço..." })
                    </div>
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.PlaceType)
                        @Html.DropDownListFor(m => m.PlaceType,
                            new SelectList(ViewBag.PlaceTypes, "Id", "Name"),
                            new { @class = "form-control", id = "PlaceType" })
                    </div>
                    <div class="col-md-2">
                        <label for="btnFind" class="control-label" style="margin-bottom: 5px; padding: 0">&nbsp;</label>
                        <button id="btnFind" type="submit" class="form-control btn btn-primary">Buscar</button>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-9">
        <p><b>Estabelecimentos</b></p>
        
        <div class="row">
            <div class="col-md-12">
                
                <table class="table">
                    <tr>
                        <th>Nome</th>
                        <th>Tipo</th>
                        <th>Cidade</th>
                        <th>Estado</th>
                        <th>Avaliações</th>
                        <th></th>
                    </tr>

                    @foreach (var place in Model.Places)
                    {
                        <tr>
                            <td>@place.Name</td>
                            <td>@place.Type</td>
                            <td>@place.City</td>
                            <td>@place.State</td>
                            <td>@place.EvaluationQuantity</td>
                            <td><a href="place/view/@place.Id" class="btn btn-success">Visualizar</a></td>
                        </tr>
                    }

                </table>

            </div>

        </div>
    </div>

    <div class="col-md-3">
        @Html.ActionLink("Cadastrar Estabelecimento", "Create", "Place", null, new { @class = "btn btn-primary pull-right" })
    </div>

</div>